### PR TITLE
Updated to version 0.16.18

### PR DESCRIPTION
**Pull request by Fank**

### CODE REVIEW

**Comment by seigieu** [comment]
Can I somehow update factorio in docker without need to wait for pull to be accepted?

**Comment by Fank** [comment]
sure :ship:

**Comment by seigieu** [comment]
Merge!! :D Yupi !! Thx 👍

**Comment by seigieu** [comment]
But still... is there a command to overwrite for example `-e VERSION=0.16.18 -e SHA1=add8b48f44a24d4ae474843f57b66cfc97749d3d ` (this one does not work, as it seems download of game source is done while pulling container rather than creating it - may be wrong here)

**Comment by Fank** [comment]
Nope, it will be downloaded in the image build process.
Not while pulling it.

**Comment by seigieu** [comment]
Then command `docker run -p 34198:34198/udp -e PORT=34198 -e VERSION=0.16.18 -e SHA1=add8b48f44a24d4ae474843f57b66cfc97749d3d -v /docker/factorio2:/factorio --name factorio2 --restart=always dtandersen/factorio` did not work for me ;(

**Comment by Fank** [comment]
Don't use the env use the tag.

```
sudo mkdir -p /opt/factorio
sudo chown 845:845 /opt/factorio
sudo docker run -d \
  -p 34197:34197/udp \
  -p 27015:27015/tcp \
  -v /opt/factorio:/factorio \
  --name factorio \
  --restart=always  \
  dtandersen/factorio:0.16.18
```

**Comment by seigieu** [comment]
I use, still there is some delay before tag is available. And (know, shame on me) don't like to wait and glare into screen 😢

**Comment by Fank** [comment]
All of these update PRs are automated (and i don't receive infos about...) the build process could take up to 30min. So if there a new auto created PR, mention me and ill merge it.
The idea of maintaing it by yourself takes a lot of work, and time to always keep it up2date. Thats the reason why i automated the version PRs (https://github.com/Fankserver/docker-factorio-watchdog).

**Comment by seigieu** [comment]
I understand. So it can't be merged automatically? 📦

**Comment by dtandersen** [comment]
It's pretty easy to fork it and set docker hub for auto builds.

**Comment by seigieu** [comment]
tbh im very fascinated about docker, but still don't have time to even get to know how to build basic file. Not saying how to modify one and compile it. My knowledge about docker ends at "it can be only downloaded from docker repository" 🤣

**Comment by dtandersen** [comment]
```
git clone https://github.com/dtandersen/docker_factorio_server.git
cd 0.16
docker build -t myfactorio .
docker run ... myfactorio
```

**Comment by seigieu** [comment]
That easy? 😆 👍 🥇

**Pull request merged**
