### PR TITLE
Add possibility to use a whitelist

### PR DESCRIPTION
**Pull request by gnomus**

### CODE REVIEW

**Comment by dtandersen** [comment]
I think this would prevent anyone besides Rseding91 and Oxyd from connecting. It's probably better only to add `--server-whitelist $CONFIG/server-whitelist.json` if server-whitelist.json exists.

**Comment by gnomus** [comment]
Sounds good, I will update the pullrequest in a minute

**Comment by gnomus** [comment]
@dtandersen I removed the copy part.

The commandline option can be added staticly if the file does not exist the Server just ignores it.

**Comment by dtandersen** [comment]
Cool. I merged it. It'll be on 0.15-dev until the next release.

**Pull request merged**
