### PR TITLE
Add script to optionally automatically update mods in server start

### PR DESCRIPTION
**Pull request by ALovedOne**
Should be backwards compatible with existing functionality since you have to opt in.

Had to update the Docker file to keep curl around and added a the jq package.

### CODE REVIEW

**Comment by DBendit** [comment]
Since you're adding `jq` anyway, could you instead pull username and token from the `server-settings.json` file? Then you wouldn't need to add additional environment variables or a new mount.

**Comment by SuperSandro2000** [comment]
You should check SHA1 if the download is corrupt.

**Comment by patschi** [comment]
@SuperSandro2000 Do you have any idea where to get the hash from? I've searched their website, google'd around - I was not able to find any source where to get the hash from.

**Comment by DBendit** [comment]
@patschi https://wiki.factorio.com/Mod_portal_API shows a sha1 field in the Releases object

**Comment by SuperSandro2000** [comment]
Eg https://mods.factorio.com/api/mods/Sandros-fixes

So you need to do one more API request before you can download the mod.

**Comment by ALovedOne** [comment]
Added checking SHA1 hashes instead of the hacky way to check if the file downloaded correctly

**Comment by DBendit** [comment]
> Added checking SHA1 hashes instead of the hacky way to check if the file downloaded correctly

:+1: for this change. I'd still like to see credentials pulled from `server-settings.json`.

**Comment by dtandersen** [comment]
You can test with the "modupdater" tag on docker hub.

**Pull request merged**
