### PR TITLE
0.17 debugging

### PR DESCRIPTION
**Pull request by dtandersen**
Currently the map generator is crashing:

```
factorio_1  | + /opt/factorio/bin/x64/factorio --create /factorio/saves/_autosave1.zip --map-gen-settings /factorio/config/map-gen-settings.json --map-settings /factorio/config/map-settings.json
factorio_1  |    0.000 2019-02-26 19:52:22; Factorio 0.17.0 (build 42971, linux64, headless)
factorio_1  |    0.000 Operating system: Linux
factorio_1  |    0.000 Program arguments: "/opt/factorio/bin/x64/factorio" "--create" "/factorio/saves/_autosave1.zip" "--map-gen-settings" "/factorio/config/map-gen-settings.json" "--map-settings" "/factorio/config/map-settings.json"
factorio_1  |    0.000 Read data path: /opt/factorio/data
factorio_1  |    0.000 Write data path: /opt/factorio [32698/40188MB]
factorio_1  |    0.000 Binaries path: /opt/factorio/bin
factorio_1  |    0.005 System info: [CPU: Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz, 2 cores, RAM: 3789 MB]
factorio_1  |    0.005 Environment: DISPLAY=<unset>, WAYLAND_DISPLAY=<unset>
factorio_1  |    0.005 Running in headless mode
factorio_1  |    0.010 Loading mod core 0.0.0 (data.lua)
factorio_1  |    0.045 Loading mod base 0.17.0 (data.lua)
factorio_1  |    0.200 Loading mod base 0.17.0 (data-updates.lua)
factorio_1  |    0.273 Checksum for core: 3857511955
factorio_1  |    0.273 Checksum of base: 738832761
factorio_1  |    0.670 Info PlayerData.cpp:69: Local player-data.json unavailable
factorio_1  |    0.670 Info PlayerData.cpp:74: Cloud player-data.json unavailable
factorio_1  |    0.671 Custom inputs active: 0
factorio_1  |    0.673 Factorio initialised
factorio_1  |    0.673 Info GlobalContext.cpp:677: Waiting for child processes to exit:
factorio_1  |    0.690 Goodbye
factorio_1  |    0.000  Error Util.cpp:75: "grass" is not a valid autoplace control name.
```

### CODE REVIEW

**Comment by jasonwc** [comment]
Was curious to see if anyone else had solved this in other Docker image repos. Pulled the 0.17 image from [here](https://hub.docker.com/r/goofball222/factorio) and ran it with the same issue:

```

**Comment by notgne2** [comment]
only just realized this PR already existed, you can work around the grass issue by just nulling out the map gen settings for now

**Comment by dtandersen** [comment]
Well, it loads now.

Use tag `0.17-debug`.

**Comment by notgne2** [comment]
gonna give it a try, fixed the merge issues on my PR after the rebase, so now it'll make whitelist work correctly

**Pull request merged**
