### PR TITLE
Allow override of start options (for scenario support)

### PR DESCRIPTION
**Pull request by dtandersen**
What do you think of this approach? You can start factorio with any desired options.

### CODE REVIEW

**Comment by dtandersen** [comment]
I removed tini, not sure it did anything. Map is properly saved when docker stops.

```
22.305 Received SIGTERM, shutting down
  22.305 Info MainLoop.cpp:315: Saving map as /opt/factorio/saves/_autosave1.zip
```

**Comment by Fank** [comment]
LGTM :ship:

**Comment by dtandersen** [comment]
It won't work the way I wanted since CMD won't process shell expansion when used by ENTRYPOINT.

**Comment by Fank** [comment]
It will

**Comment by Fank** [comment]
Check https://github.com/Fank/docker-starmade

**Pull request closed without merging**
