### PR TITLE
Updated to version 0.16.43

### PR DESCRIPTION
**Pull request by Fank**

### CODE REVIEW

**Comment by RowanTaubitz** [comment]
The PR is automated, any reason the merge is manually done?

**Comment by Fank** [comment]
Will change to automated now.

**Comment by Fank** [comment]
@dtandersen https://github.com/Fankserver/docker-factorio-watchdog/commit/1d51ab8cb06c96f0f69f110579480c50872cdf74#diff-0a4a2643911c0d8ba7d0bca87a923509 branch with PR -> master push and tag

**Comment by dtandersen** [comment]
Fine to automate it. It's been working great!

**Pull request merged**
