### PR TITLE
Running factorio server as non-root

### PR DESCRIPTION
**Pull request by emichael**
Probably not entirely necessary, but it's a nice hardening step

### CODE REVIEW

**Comment by emichael** [comment]
Should probably add a note about adding a user called fdaemon with the correct UID to the host system, as well.

**Comment by dtandersen** [comment]
I'm torn, because it makes it harder to setup. You have to chown files on the host system to 8415:8415.

**Comment by emichael** [comment]
It's definitely not perfect, but I think the added bit of security is worth it.

Also, I haven't tested it thoroughly, but I *think* it will work even if the files are only accessible to root on the host system. It seems like docker does something under the hood to give processes running in containers access to all files in their volumes.

**Comment by VonOx** [comment]
@dtandersen not really, you can use mapping at the container creation

```
docker run -d -p 34197:34197/udp -p 27015:27015/tcp \
  -v /tmp/factorio:/factorio \
  --name factorio \
  --restart=always  \
  -e PGID=<gid> -e PUID=<uid> \
  dtandersen/factorio
```

This map host user to container user, so any choosed user on the host can run the container

See [this post](https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf) 

This method is used with [this teamspeak 3 container](https://github.com/linuxserver/docker-gsm-ts3#user--group-identifiers) and it works well

**Pull request merged**
